name: Deploy NestJS GraphQL

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          set -e

          cd ${{ secrets.VPS_DEPLOY_PATH }} || { echo "Project folder not found!"; exit 1; }

      - name: Git Pull
      - run: |
          git reset --hard HEAD
          git clean -fd
          git pull origin dev

      - name: Creating .env
      - run: |
          touch .env
          echo "${{ secrets.ENV }}" > .env
          chmod 600 .env  # Secure the .env file

      - name: Managing Package
      - run: |
          npm install
          npm run postinstall

      - name: Seeding database
      - run: |
          npm run seed
      
      - name: Building App
      - run: |
          npm run build

      - name: Start pm2
      - run: |
          pm2 restart graphql-test || pm2 start dist/main.js --name graphql-test
          pm2 save
          echo "Deployment completed successfully!"
          EOF