name: Deploy NestJS GraphQL

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          set -e

          # Navigate to the project directory
          cd ${{ secrets.VPS_DEPLOY_PATH }} || { echo "Project folder not found!"; exit 1; }

          # Pull the latest code
          git pull origin main

          # Create the .env file from GitHub Secret
          echo "${{ secrets.ENV_FILE }}" > .env
          chmod 600 .env  # Secure the .env file

          # Install dependencies
          npm install

          # Build the application
          npm run build

          # Restart the application using PM2
          pm2 restart graphql-test || pm2 start dist/main.js --name graphql-test

          # Save PM2 state
          pm2 save

          echo "Deployment completed successfully!"
          EOF